name: Mark Stale Issues and PRs in Multiple Repos

on: [push]

jobs:
  mark-stale-items:
    runs-on: ubuntu-latest
    steps:
    - name: Mark Stale Issues and PRs
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.META_PROJECT_SERVICE_PAT }}
        script: |
          const MAX_DAYS_OLD = 30; // Example: 30 days of inactivity
          const repos = ["realestate-scrapper"]; // List of repositories to process
          const staleLabel = "Stale";

          // Function to calculate the date N days ago in YYYY-MM-DD format
          function getDateNDaysAgo(days) {
            const date = new Date();
            date.setDate(date.getDate() - days);
            return date.toISOString().split('T')[0];
          }

          const date30DaysAgo = getDateNDaysAgo(MAX_DAYS_OLD);

          for (const repo of repos) {
            // Function to label stale items
            async function labelStaleItems(type) {
              const searchQuery = `repo:${repo} is:open updated:<${date30DaysAgo} is:${type}`;
              
              // Find stale items
              const staleItems = await github.rest.search.issuesAndPullRequests({
                  q: searchQuery
              });

              // Label stale items
              for (const item of staleItems.data.items) {
                  await github.rest.issues.addLabels({
                      owner: context.repo.owner,
                      repo: repo,
                      issue_number: item.number,
                      labels: [staleLabel]
                  });
                  console.log(`Labeled ${type} #${item.number} as stale in ${repo}`);
              }
            }

            // Label stale issues
            await labelStaleItems('issue');

            // Label stale PRs
            await labelStaleItems('pr');
          }
